import { ArrowRight, Bot, Box, Check, CircleGauge, Cloud, Cpu, Database, Gamepad2, HardDrive, Headphones, RefreshCw, Server, ShieldCheck, Sparkles, Terminal, Zap } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { siteConfig } from "@/config/site";
import { useSiteStatus } from "@/hooks/use-site-data";
import type { ServiceStatus } from "@/types/hosting";

export function SectionHeading({ eyebrow, title, description, align="left" }: { eyebrow:string; title:string; description?:string; align?:"left"|"center" }) { return <div className={cn("max-w-2xl",align==="center"&&"mx-auto text-center")}><span className="eyebrow">{eyebrow}</span><h2 className="section-title">{title}</h2>{description&&<p className="section-copy">{description}</p>}</div>; }

export function Hero() { return <section className="hero-grid overflow-hidden border-b border-border"><div className="site-container grid min-h-[610px] items-center gap-10 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-20"><div><span className="eyebrow"><Sparkles className="size-3.5"/> NuvyCloud • Rede Lua</span><h1 className="mt-5 max-w-3xl font-display text-4xl font-extrabold leading-[1.08] text-foreground sm:text-5xl lg:text-6xl">Sua nuvem.<br/><span className="text-primary">Seus projetos.</span><br/>Seu controle.</h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground sm:text-lg">Hospedagem simples para colocar seu bot ou servidor Minecraft online sem complicação.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild><Link to="/planos">Ver planos <ArrowRight/></Link></Button>{siteConfig.clientAreaUrl&&<Button size="lg" variant="outline" asChild><a href={siteConfig.clientAreaUrl}>Área do Cliente</a></Button>}</div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><Check className="size-3.5 text-brand-green"/> Planos acessíveis</span><span className="inline-flex items-center gap-1.5"><Check className="size-3.5 text-brand-green"/> Upgrade fácil</span><span className="inline-flex items-center gap-1.5"><Check className="size-3.5 text-brand-green"/> Suporte humano</span></div></div><InfrastructureVisual/></div></section>; }

const visualStatusLabel: Record<ServiceStatus,string> = { operational:"OPERACIONAL", degraded:"INSTÁVEL", maintenance:"MANUTENÇÃO", offline:"INDISPONÍVEL", unknown:"AGUARDANDO" };
function InfrastructureVisual() {
  const query=useSiteStatus();
  const service=(key:string)=>query.data?.find(item=>item.serviceKey===key);
  const nodes=[[Bot,"BOT",service("bots")],[Gamepad2,"MINECRAFT",service("minecraft")],[Server,"PAINEL",service("panel")],[CircleGauge,"API",service("billing")]] as const;
  return <div className="relative mx-auto w-full max-w-xl"><div className="infra-orbit" aria-hidden/><div className="relative grid grid-cols-2 gap-3 p-4 sm:p-8">{nodes.map(([Icon,name,item],i)=><div key={name} className={cn("status-panel",i%2===1&&"translate-y-8")}><div className="flex items-center justify-between"><Icon className="size-5 text-primary"/><span className={cn("status-dot",item?.status==="operational"&&"bg-brand-green",item?.status==="degraded"&&"bg-brand-yellow",item?.status==="offline"&&"bg-destructive")}/></div><p className="mt-8 text-[10px] font-bold tracking-[0.18em] text-muted-foreground">{name}</p><p className="mt-1 font-display text-base font-bold text-foreground">{item?visualStatusLabel[item.status]:"AGUARDANDO"}</p></div>)}</div><div className="absolute left-1/2 top-1/2 -z-10 h-px w-4/5 -translate-x-1/2 bg-border"/></div>;
}

const benefits=[[Zap,"Ativação automatizada","Seu serviço pode ser provisionado automaticamente após a confirmação do pedido."],[Terminal,"Painel simples","Gerencie arquivos, console e configurações através do painel."],[Headphones,"Suporte humano","Atendimento para ajudar nos problemas mais importantes."],[RefreshCw,"Upgrade fácil","Comece pequeno e aumente seu plano quando o projeto crescer."]] as const;
export function Benefits(){return <section className="section"><div className="site-container"><SectionHeading eyebrow="Comece do seu jeito" title="Feito para começar sem complicação" description="Recursos claros, contratação direta e espaço para crescer."/><div className="mt-10 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{benefits.map(([Icon,title,text])=><article key={title} className="bg-surface p-6"><Icon className="size-6 text-brand-yellow"/><h3 className="mt-5 font-display text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></div></section>}

export function Infrastructure(){const items=[[Cpu,"CPU","Recursos proporcionais ao plano"],[Database,"RAM","Planos de entrada com upgrade"],[HardDrive,"Storage","Espaço para seus arquivos"],[Cloud,"Rede","Estrutura preparada para crescer"]] as const;return <section className="section border-y border-border bg-surface-deep"><div className="site-container grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><SectionHeading eyebrow="Infraestrutura" title="Construída para crescer" description="A NuvyCloud começa com uma estrutura otimizada para projetos pequenos e médios, aumentando sua capacidade conforme a comunidade cresce."/><div className="grid gap-3 sm:grid-cols-2">{items.map(([Icon,label,text])=><div key={label} className="metric-card"><Icon className="size-5 text-primary"/><div><strong className="text-sm">{label}</strong><p className="mt-1 text-xs text-muted-foreground">{text}</p></div></div>)}</div></div><div className="site-container mt-10 rounded-lg border border-brand-yellow/30 bg-brand-yellow/5 p-5 text-sm leading-6 text-muted-foreground">Em vez de vender recursos que você não precisa, nossos planos começam menores para manter preços acessíveis e permitir upgrades conforme seu projeto cresce.</div></section>}

export function CTASection(){return <section className="section"><div className="site-container"><div className="cta-band"><div><span className="eyebrow">Comece pequeno</span><h2 className="mt-3 font-display text-3xl font-extrabold sm:text-4xl">Pronto para colocar seu projeto online?</h2><p className="mt-3 text-muted-foreground">Comece com um plano pequeno e faça upgrade quando precisar.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild><Link to="/planos">Ver planos</Link></Button>{siteConfig.clientAreaUrl&&<Button variant="outline" size="lg" asChild><a href={siteConfig.clientAreaUrl}>Área do Cliente</a></Button>}</div></div></div></section>}

export const featureIcons={Bot,Gamepad2,Server,ShieldCheck,Box};
